
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import "react-advanced-cropper/dist/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mealie Transformer",
  description: "Generated by Firebase Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center bg-muted/40 min-h-screen p-4 sm:p-8">
          <main className="w-full h-full flex-grow flex flex-col items-center">
            {children}
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
